### ISSUE TITLE
Verification code security

### ISSUE THREAD

**Issue by OscarSwanros** [taximaticomx/taximatico_engine#21]
Right now the verification code is a 8(?) digit one. It would be better for it to be a 4 digit (6 tops) one.

Also, codes are not being invalidated after they're used. Eg: I can verify with a code that was sent to me even if it is not the latest one sent from the latest login attempt.

**Comment by TheNaoX** [comment]
Interesting, I'll take a look on that, I kind of remember I did add security to the verification code process.
