### ISSUE TITLE
Verification API security

### ISSUE THREAD

**Issue by OscarSwanros** [taximaticomx/taximatico_engine#9]
The verification request should be a `POST` request to `/users/verification_codes/check`, not `GET`.

Also, the phone number should be sent along with the verification code to prove that the user is in fact the one who requested the code in the first place.

Also, remove the top level object from the query object, since its not JSON:

```
{
    "phone_number":  "+523121125642",
    "code" : "123456"
}
```

**Comment by TheNaoX** [comment]
See https://github.com/taximaticomx/taximatico_engine/pull/11
